library(diversitree)
library(phytools)
setwd("###")
phy = read.tree(file = 'dated_Vitaceae_nooutgroup.tre')
phy = force.ultrametric(phy)
state_file = read.csv('###')
Humidity = c(state_file$Humidity)
names(Humidity) = c(state_file$Taxon)
phy$tip.state = Humidity
sampling.f <- 0.5
lik_mu <- make.musse(phy, phy$tip.state, 3, sampling.f=sampling.f)
p <- starting.point.musse(phy, 3)
fit_mu <- find.mle(lik_mu, p[argnames(lik_mu)])
lik_mu1 <- constrain(lik_mu, lambda1 ~ lambda3)
fit_mu1 <- find.mle(lik_mu1, p[argnames(lik_mu1)])
lik_mu2 <- constrain(lik_mu, lambda1 ~ lambda2)
fit_mu2 <- find.mle(lik_mu2, p[argnames(lik_mu2)])
lik_mu3 <- constrain(lik_mu, lambda2 ~ lambda3)
fit_mu3 <- find.mle(lik_mu3, p[argnames(lik_mu3)])
lik_mu4 <- constrain(lik_mu, mu1 ~ mu3)
fit_mu4 <- find.mle(lik_mu4, p[argnames(lik_mu4)])
lik_mu5 <- constrain(lik_mu, mu2 ~ mu3)
fit_mu5 <- find.mle(lik_mu5, p[argnames(lik_mu5)])
lik_mu6 <- constrain(lik_mu, mu1 ~ mu2)
fit_mu6 <- find.mle(lik_mu6, p[argnames(lik_mu6)])
model= round(rbind(base=coef(fit_mu), equal.mu1=coef(fit_mu1, TRUE), equal.mu2=coef(fit_mu2, TRUE), equal.mu3=coef(fit_mu3, TRUE), equal.mu4=coef(fit_mu4, TRUE), equal.mu5=coef(fit_mu5, TRUE), equal.mu6=coef(fit_mu6, TRUE)), 3)
write.csv(model, file = "###_MuSSE_model.csv")
anv = anova(fit_mu1, equal.mu2=fit_mu2, equal.mu3=fit_mu3, equal.mu4=fit_mu4, equal.mu5=fit_mu5, equal.mu6=fit_mu6)
write.csv(anv, file = "###_MuSSE_anova.csv")
prior <- make.prior.exponential(1 / (2 * (p[1] - p[4])))
samples <- mcmc(lik_mu, coef(fit_mu), nstep=100, w=1,
        prior=prior, print.every=50)
w <- diff(sapply(samples[3:14], range))
samples <- mcmc(lik_mu, coef(fit_mu), nstep=10000, w=w,
        prior=prior, print.every=1000)
write.csv(samples, file = "###_MuSSE_samples.csv")
samples = read.csv(file = "###_MuSSE_samples.csv")
col <- c("#006633","#99cc33","#ffcc33")
pdf("###_MuSSE_lambada.pdf", width=10, height=10)
profiles.plot(samples[c("lambda1", "lambda2", "lambda3")], col.line=col, las=1,
xlab="Speciation rate", xlim = c(0,1),ymax = 30, lines.on.top=TRUE, n.br = 100)
dev.off()
col <- c("#006633","#99cc33","#ffcc33")
pdf("###_MuSSE_mu.pdf", width=10, height=10)
profiles.plot(samples[c("mu1", "mu2", "mu3")], col.line=col, las=1,
xlab="Extinction rate", xlim = c(0,1),ymax = 30, lines.on.top=TRUE, n.br = 100)
dev.off()
col <- c("#006633","#99cc33","#ffcc33")
pdf("###_MuSSE_net.pdf", width=10, height=10)
profiles.plot(samples[c("lambda1", "lambda2", "lambda3")] - samples[c("mu1", "mu2", "mu3")], col.line=col, las=1,
xlab="Net diversification", xlim = c(0,1),ymax = 30, lines.on.top=TRUE, n.br = 100)
dev.off()